services:
  pdl-ai:
    build: .
    image: pdl-ai:laster-beta
    container_name: pdl-ai
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
     - PDL-DB:/app/PDL-AI/home/cluster/server/
     - PDL-ROM:/app/PDL-AI/home/cluster/temp/
     - PDL-LOGS:/app/PDL-AI/logs/

volumes:
  PDL-DB:
    external: true
  PDL-ROM:
    external: true
  PDL-LOGS:
    external: true
      