services:
  pdl-ai:
    build: .
    image: pdl-ai:laster
    container_name: pdl-ai
    restart: unless-stopped
    volumes:
     - PDL-DB:/app/PDL-AI/home/cluster/rom/system/db.json
     - PDL-LOGS:/app/PDL-AI/logs/

volumes:
  PDL-DB:
    external: true
  PDL-LOGS:
    external: true
      